### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by staxfur** [MCWertGaming/foxterm#1]
These features are planed for foxterm:

# features
- [x] add missing style ansi codes
- [x] add terminal control ANSI codes
- [ ] add style to auto color
- [ ] add underline color to auto color
- [ ] make both 8 bit conversions available on color set init
- [ ] add printing function for normal printing
- [ ] add move printing function
- [ ] add printing with offset function
- [ ] add centered printing function
- [ ] Test auto color on windows
- [ ] add bel ringing
- [ ] add changing of console title
- [ ] improve comments on styles

# advanced features
- [ ] rendering class with rendering thread
- [ ] window class for stand alone rendering
- [ ] terminal preparation
- [ ] enable raw mode
- [ ] input capturing async
- [ ] input capturing real-time key press

# build system and testing
- [ ] make installable
- [ ] add ctest
- [ ] add cpack
- [ ] add integration testing
- [ ] add clang-format action
- [ ] add dependabot
- [ ] add CodeQL
- [ ] enable all errors and turn them into warnings
- [ ] add clang-tidy action
- [ ] lint cmake
- [ ] lint ci scripts

# demo and docs
- [ ] add short demo
- [ ] document hex conversion in code
- [ ] document auto colors in code
- [ ] document 8 bit conversion
- [ ] add real documentation
- [ ] add project site
- [ ] add readme
- [ ] add Code of Conduct
- [ ] add issue templates
- [ ] add PR templates
- [ ] add contribution guidelines

# clean up
- [ ] simplify code
- [x] shorten namespace name
- [ ] shorten function names
- [x] split unit testing
